feat(sekoia-connector): Init OpenCTI SEKOIA.IO connector
SEKOIA-IO/opencti-connector pull request #1
Opened 2020-07-29 13:35 UTC by Darkheir

2020-08-25 09:07 UTC, gaelmuller requested changes

2020-08-25 09:07 UTC, gaelmuller commented on docker-compose.yml
> +      - OPENCTI_TOKEN=df8635b1-39b5-41c2-8873-2f19b0e6ca8c
```suggestion
      - OPENCTI_TOKEN=ChangeMe
```

2020-08-25 09:07 UTC, gaelmuller commented on src/sekoia.py
> +            time.sleep(60)
maybe put the frequency in the configuration ?

2020-08-31 09:21 UTC, Darkheir commented on src/sekoia.py
> +            time.sleep(60)
You think this is a setting that it would be useful to change ?

2020-09-01 08:56 UTC, gaelmuller approved these changes

2020-09-02 14:28 UTC, merged